### PR TITLE
Self nominate Vijay Samuel - eBay

### PR DESCRIPTION
**Pull request by vjsamuel**

### CODE REVIEW

**Review by justinabrahms — APPROVED** [review]

**Comment by jpkrohling** [comment]
The intent of the schedule was too close nominations on 6 Oct 2022, but I missed the other place stating this deadline (7 Oct 2022 23:59 UTC). Therefore, this nomination still in, given it received the necessary support.

**Comment by bogdandrutu** [comment]
+1

**Comment by Aneurysm9** [comment]
I support this nomination.

**Comment by reyang** [comment]
+1

**Comment by jpkrohling** [comment]
Merging, as at least 3 members of standing from different companies are supporting this nomination, including the nominee himself.

**Review by jpkrohling — APPROVED** [review]

**Comment by alolita** [comment]
I support.

**Pull request merged**
