### PR TITLE
Self-nomination: jpkroehling for Governance Committee 2023

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by mensis-labs** [comment]
LGTM 💯 🚀 👍🏼

**Comment by claudiobastos** [comment]
Awesome! 👍🏽 💯 🥇

**Review by Tsugami — APPROVED** [review]

**Comment by cartersocha** [comment]
+1

**Review by yurishkuro — APPROVED** [review]

**Review by trask — APPROVED** [review]

**Comment by EzzioMoreira** [comment]
+1

**Comment by apolzek** [comment]
+1

**Comment by graciellamauri** [comment]
Great!

**Comment by trask** [comment]
I support

**Pull request merged**
