### PR TITLE
Nominate Josh and Ryan as C++ approver and maintainer

### PR DESCRIPTION
**Pull request by tedsuo**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@jmacd and @rnburn please confirm your commitment

**Comment by rnburn** [comment]
Yes, I'd be interested.

**Comment by jmacd** [comment]
Yes, I'm on board.

**Comment by SergeyKanzhelev** [comment]
welcome! Let me know when you are ready to start and need repo created

**Pull request merged**
