### PR TITLE
Update how-to-handle-public-calendar.md

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
Related to #763

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Can somebody test it? I seem to configure it. Need to join the room and hangout for >10minutes for recording to be uploaded. @eddynaka can you help with it?

**Comment by SergeyKanzhelev** [comment]
@eddynaka confirmed it works. So we can start using this room now

**Comment by eddynaka** [comment]
> @eddynaka confirmed it works. So we can start using this room now

Sorry for not answering...
BUT, yes, I was able to configure the zoom account to enable any user to join without waiting the host.

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/governance-committee can anybody approve this, please?

**Comment by yurishkuro** [comment]
Can we fix the TBD?

**Comment by SergeyKanzhelev** [comment]
> Can we fix the TBD?

done. Colors were not used anyway

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
