### PR TITLE
community-members: Fix typo.

### PR DESCRIPTION
**Pull request by Oberon00**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please fix the CLA, I know that Dynatrace signed it as a company, probably you don't have the company email setup.

**Comment by Oberon00** [comment]
Yes it seems so. I'm on it.

**Comment by Oberon00** [comment]
(Just commenting again to retrigger the CLA check)

**Comment by Oberon00** [comment]
(Just commenting again to retrigger the CLA check again, after associating the GH and Linux ID accounts)

**Pull request merged**
