### PR TITLE
Add Dynatrace people as contributors

### PR DESCRIPTION
**Pull request by AloisReitbauer**
As discussed offline, I added the list of people who are committed to contribute to OpenTelemetry across all project we are going to contribute to.

### CODE REVIEW

**Comment by AloisReitbauer** [comment]
Comment for revalidate CLA

**Comment by bogdandrutu** [comment]
Can you please file an issue for every person you add, just to make sure we follow the process?

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer I moved you to approver of the specs branch as we yet to define process and responsibility of a Technical Committee of OpenTelemetry. I made this change myself to expedite processing of this PR and avoid back and forth. Feel free to reach out and discuss.

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer it's great to see a commitment from Dynatrace! Welcome to the project.

Initial idea was to bootstrap the project with active OpenCensus and OpenTracing members for specific languages. And follow the standard policies for community membership. We expect that new approvers can point to a demonstrable history of contributions to OpenTelemetry repos / SIGs. But taking into consideration the early stage of the project and amount of work we need to do to bootstrap it we are accepting this nomination.

**Comment by bogdandrutu** [comment]
LGTM

**Comment by bogdandrutu** [comment]
For the record Dynatrace was an important player in the W3C standard, so we took that in consideration.

**Pull request merged**
