### PR TITLE
Add .NET auto-instrumentation info to community-members.md

### PR DESCRIPTION
**Pull request by macrogreg**
.NET now has an SDK SIG/repo and an auto-instrumentation SIG/repo. Adding corresponding sub-section under the .NET section.

### CODE REVIEW

**Review by mtwo — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by macrogreg** [comment]
This PR is currently blocked on approval by ALL members of the committee.
Apologies for the noise, I am a little surprised that so many people need to approve such a simple change.
Perhaps, in the future only a few committee member approvals may be sufficient?

Anyway, tagging required reviewers. Thank you!

@tedsuo
@sarahnovotny
@lizthegrey
@bogdandrutu
@bhs
@yurishkuro
@ccaraman

**Comment by macrogreg** [comment]
Thanks for merging this, @SergeyKanzhelev . Looks like you had the right permissions. :)

**Comment by SergeyKanzhelev** [comment]
sorry it fell off the radar. I waited for additional feedback (if any) and then lost track of it

**Comment by macrogreg** [comment]
No worries. Thank you! ))

**Pull request merged**
