### PR TITLE
Update governance-committee-candidates.md

### PR DESCRIPTION
**Pull request by avillela**

### CODE REVIEW

**Comment by trask** [comment]
I support

**Comment by trask** [comment]
@avillela don't worry about the `table-check` failure, I'm looking into what's going on #2368

**Comment by svrnm** [comment]
I support

**Comment by danielgblanco** [comment]
I support

**Review by danielgblanco — APPROVED** [review]

**Review by trask — APPROVED** [review]

**Comment by lizthegrey** [comment]
belated support!

**Pull request merged**
