### PR TITLE
Nominate Michael Hausenblas for GC 2022 election

### PR DESCRIPTION
**Pull request by Aneurysm9**
I nominate Michael Hausenblas (@mhausenblas) as a candidate for the OTel Governance Committee, considering his contributions in the OTel community around end-users and best practices.

### CODE REVIEW

**Comment by lizthegrey** [comment]
Seconded.

**Comment by mhausenblas** [comment]
Thank you and I gladly accept my nomination!

**Review by lizthegrey — APPROVED** [review]
Three members of standing have ratified including one self-ratification.

**Comment by svrnm** [comment]
I support this nomination :-)

Just a formality:

> Anyone may nominate either themselves or someone else to be a candidate in the election. To be ratified as a candidate, the nominee must accept the nomination and three Members of Standing (including the nominator, if she/he has standing) from **three different employers**, must endorse the nomination.

@Aneurysm9 & @mhausenblas you both are with Amazon, right? So I fixed that.

**Pull request merged**
