### PR TITLE
Self-nomination: Alolita Sharma for Governance Committee Election 2022

### PR DESCRIPTION
**Pull request by alolita**
Self nomination with statement of candidature for Alolita Sharma.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
I support this nomination.

**Comment by alolita** [comment]
@jpkrohling @lizthegrey I missed the broken image link. But the image is uploaded. Can you please fix in final compilation. 🙏

**Comment by sharrmander** [comment]
I support this nomination!

**Comment by jkowall** [comment]
Definitely supporting Alolita for the governance committee!

**Comment by lizthegrey** [comment]
support as well.

**Comment by ericmustin** [comment]
I support this nomination 👍

**Comment by jpkrohling** [comment]
I support this nomination.

PS: @alolita, I tried to fix your PR, but apparently, the branch is part of this repository and not of a fork, so I can't adjust it. Feel free to cherry-pick the changes from here: https://github.com/jpkrohling/community/tree/alolita-gc-appl

**Review by lizthegrey — APPROVED** [review]

**Comment by reyang** [comment]
I support this nomination.

**Comment by vishiy** [comment]
i support  @alolita 's nomination

**Pull request merged**
