### PR TITLE
Split out calendar invite groups

### LINKED ISSUE #1414: Public calendaring issue/improvement
We are having some problems with the Google calendar syncing (for those who have joined [opentelemetry-calendar@googlegroups.com](mailto:opentelemetry-calendar@googlegroups.com)). Likely because I updated too many meetings while giving all of the Zoom meetings separate ids/names, and hit some Google calendar spamming limits (by the way, sorry for the spam 😅).

I'd like to propose a change (originally raised by @tylerbenson), and create separate "invitee" google groups per meeting so that we aren't spamming so many updates for every meeting (there are currently >150 people in opentelemetry-calendar@googlegroups.com).

If we do this, I'd like to remove opentelemetry-calendar@googlegroups.com from the meetings, and email that list letting them know about the new per-meeting google groups they can join instead.

If we still need a list for all meetings, we can create that separately (e.g. opentelemetry-calendar-all@googlegroups.com) and hopefully it should be much smaller number of people who want to be in that group.

(and yes, I'm volunteering to make these changes and document them in this repo, I've lost too much time on the calendar in the last days to not hopefully see this through to a better place 😅)

### PR DESCRIPTION
**Pull request by trask**
Closes #1414

Replaces #1415 now that we have a Google Workspace (@opentelemetry.io).

~Currently built on top of #1787, will rebase once that's merged.~

Proposal for cutting over to the new Google Workspace owned calendar (once this PR is approved and ready to be merged):
* (re-) copy all the meeting over to make sure all latest changes are copied over
* post to each slack channel with:
  * link to the new calendar
  * link to the relevant google group(s) to join for synchronization
  * maintainers need to join google group [calendar-edit-permission@opentelemetry.io](https://groups.google.com/a/opentelemetry.io/g/calendar-edit-permission)
* delete all upcoming meetings from the previous calendar (include note about cutover when deleting for those who are syncing)
* put a single (recurring) meeting on the previous calendar that redirects people to the new calendar

Note: zoom links will _not_ change, so hopefully this cutover will be less disruptive compared to when we split out the zoom links earlier this year to fix the recorded meeting names.

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]

**Review by svrnm — APPROVED** [review]
lgtm

**Review by danielgblanco — APPROVED** [review]
Checked links. LGTM!

**Comment by danielgblanco** [comment]
Are the actions in the PR description (send message on Slack, copy invites, send upcoming events, etc) going to be performed by the SIGs themselves or is there a single person driving all the actions?

**Comment by tylerbenson** [comment]
(I would love to see this finished up so I can properly cleanup my calendar. Is there any way I can help?)

**Pull request merged**
