### PR TITLE
Add note about ranked voting and alternative voting systems

### PR DESCRIPTION
**Pull request by jpkrohling**
Based on today's GC meeting, I added the summary of the discussion about the evaluated voting systems, along with our requirements.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Review by sharrmander — APPROVED** [review]
I support the election committee evaluating other voting options which allow for ranked choice voting

**Comment by bhs** [comment]
Having personally run a CIVS election, the actual *voting* part seemed great... BUT the registration situation was a minor nightmare since it's email-only.

If there was a way to do GitHub-authenticated ranked-choice voting, that would certainly be ideal!

**Comment by lizthegrey** [comment]
> Having personally run a CIVS election, the actual _voting_ part seemed great... BUT the registration situation was a minor nightmare since it's email-only.
> 
> If there was a way to do GitHub-authenticated ranked-choice voting, that would certainly be ideal!

K8s has it configured but we don't.

https://github.com/kubernetes/community/blob/master/elections/teams/README.md

**Comment by jpkrohling** [comment]
> K8s has Elekto configured but we don't.

I can commit to checking with the CNCF if we can get their help in running Elekto next year.

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
