### PR TITLE
Update eBPF doc to be owned by GC

### PR DESCRIPTION
**Pull request by dyladan**
Related to #1147 

TODO when the PR merges
- Update calendar link

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@yonch Please update links to the eBPF meeting notes anywhere else you think it may be linked from.

**Comment by tigrannajaryan** [comment]
Linked from old to new doc and old doc is now readonly.

**Comment by tigrannajaryan** [comment]
I can't see eBPF on Otel calendar to update the link.

**Review by arminru — APPROVED** [review]

**Comment by yonch** [comment]
Thank you @tigrannajaryan! I believe the meeting notes were on a personal or corporate account before, so much better on an Otel account.

The meeting is on hiatus, we plan to bring it back in the coming weeks. Will link to the new location of the notes when we reinstate it.

**Comment by tigrannajaryan** [comment]
https://github.com/orgs/open-telemetry/teams/technical-committee we need more approvals to merge this.

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee we need more approvals to merge this.

**Pull request closed without merging**
