### PR TITLE
New meeting recording workflow

### LINKED ISSUE #451: Suggestion: Youtube uploader tool - add the room name to the meeting title
Room can be extrapolated from the Splain's auto-generated name. See screenshot - there are different names there:

  image

There are only [three meeting rooms](https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md) we are using and the name of the meeting room can be added to the meeting title by the tool.

@eddynaka can you do this?

### LINKED ISSUE #715: Add SIG names to Youtube uploads and organize them into playlists again
It seems that the videos used to have SIG name in them and they used to be filed under a SIG-specific playlist, but it stopped around October 2020. Could we bring this back? It's difficult to find relevant videos the way it is right now.

Example here: https://www.youtube.com/watch?v=QnbY2qxHBW0&list=PLVYDBkQ1Tdyw5ccPWGur1s2Ohnt9f6eEO

### LINKED ISSUE #863: Meeting recordings not being uploaded to Youtube: migrate the tool to a GH action
It seems the uploads of meeting recordings have stopped. The last one is from more than a month ago:

Looking at here: https://www.youtube.com/channel/UCHZDBZTIfdy94xMjMKz-_MA/videos

### LINKED ISSUE #935: The process of uploading Go SIG meet on Youtube is slow
For Go SIG meet, I can only watch the recording in the next week. Could we speed up this process?

Pick the meet `Go SIG meet, December 16, 2021, 13:00 PT` as an example, it has been two days, and I see no recording for Go SIG on Youtube.

### LINKED ISSUE #964: Meeting names: "This is a calendar meeting"
After the switch to the new way meetings scheduled, some recordings have a good names, some (majority) are called "This is a calendar meeting".  @mtwo any idea why the difference and is there a way to have good names for all meetings?

### LINKED ISSUE #1406: Decision about public video recordings
There is a growing concern that the meeting recordings could be used to create impersonations of community members. Some members have asked that we stop publishing public recordings.

The following options were proposed in the maintainers SIG call and a vote the preferred option was suggested:

👍 Leave the recordings up (accept the risk)
😄 Flag the videos as not to be used in training data (wouldn’t protect against targeted attacks, but still helpful)
🎉 Make the recordings private to the community (unlisted on YouTube by default, accessible via playlist or links in a doc)
❤️ Make the recordings expire or become unlisted after some time period (or only accessible to GC / admins eventually)
🚀 Rely on transcripts
👀 Rely on manual notes

More information as per @dyladan's comment below:

> There are several other factors at play here aside from the preferences of the people voting on github. Specifically, we may have legal obligations relating to the right to be forgotten in certain jurisdictions. I'll reach out to the CNCF to see if they can provide guidance in this area. The people voting here are not a representative sample of affected people. Most people who join the meetings are not maintainers and are unlikely to see community issues like this one. Most of them are also not public personas and they may not be as comfortable with public recordings of themselves as others who are more used to being public. As mentioned by others, some changes may also require charter changes which falls under the purview of the GC
> 
> We should also consider that the solution may involve aspects of multiple options in the poll. I think nearly everyone agrees some expiration/retention policy is an improvement on what we already have. We know from the maintainers meeting that some people are definitely using these recordings and we don't want to exclude them from the project, but most of the usefulness of the recordings is lost after a short period of time. We need to make sure that we're balancing the need for privacy with the usefulness of the public recordings. I think most would also agree that better meeting notes would be an improvement for everyone, not just people who can't attend meetings.

**_It is okay to vote for multiple options_**.

### PR DESCRIPTION
**Pull request by trask**
Resolves #1406
Resolves #964
Resolves #935
Resolves #863
Resolves #715
Resolves #451

New meeting workflow is to no longer upload meetings to YouTube, but instead to make Zoom cloud recordings available via Google spreadsheet using Zapier integration:

image

Here's an example recording: https://zoom.us/rec/share/6VEDYb5zV-hDAT-mDr5W_A9FDYrE6WyTeWMRWz8xqKgJKOypdEwr9rDDerW2xMDj.zz6qA84Yxqces8s4

Note that this includes Zoom chat messages which YouTube videos were previously missing.

The naming relies on splitting out separate Zoom ID per meeting series, which is documented in #1415.

I verified that all Zoom cloud recordings exist back to the beginning of the project, so expiring too soon doesn't appear to be a problem, though we may still wish to expire them (deferring this issue to #562).

Note that this Google spreadsheet only contains meeting recordings starting from 4/10/2023 (when the Zoom meeting links were split out to have unique ids/names, and when the Zapier integration was enabled). If you need a recording prior to that, please open an issue in this repo and we will do our best to find it in the Zoom cloud archives.

### CODE REVIEW

**Comment by tylerbenson** [comment]
Is this spreadsheet publicly accessible?  How can I access it?

**Comment by weyert** [comment]
One of the benefits of hosting it on Youtube is that it is one of the places that typically is not blocked on firewalls while Zoom.us is. Now people need to circumvent firewall blocks via VPNs to be able to watch recordings.

**Comment by cwegener** [comment]
> Is this spreadsheet publicly accessible? How can I access it?

Link is in this PR

**Review by mattmccleary — APPROVED** [review]

**Review by tedsuo — APPROVED** [review]

**Review by dyladan — APPROVED** [review]

**Review by weyert — CHANGES_REQUESTED** [review]
How are you supposed to access the videos when you can't use Zoom?

**Comment by cwegener** [comment]
Is the Zapier workflow still running?
The Google Sheet has not been updated for a week.

**Comment by trask** [comment]
> Is the Zapier workflow still running? The Google Sheet has not been updated for a week.

ya, it hit the monthly limit on my free account. we've opened a request to the CNCF to upgrade us to a paid account.

**Review by weyert — CHANGES_REQUESTED** [review]
Needs clarification how videos can be accessed when you unable to access Zoom recordings

**Comment by mx-psi** [comment]
> Needs clarification how videos can be accessed when you unable to access Zoom recordings

We don't have such clarification for the previous workflow, despite Youtube [being blocked on several countries](https://en.wikipedia.org/wiki/Censorship_of_YouTube#Countries_where_access_to_YouTube_is_currently_blocked). I think it's good to have a documented workaround, but I don't think we need to clarify it on this PR, given that there was no clarification for the previous workflow.

**Review by jpkrohling — APPROVED** [review]
To confirm: this doesn't require any actions from people attending or hosting the meetings, right? It's just a different workflow for dealing with the recordings themselves.

**Comment by trask** [comment]
> this doesn't require any actions from people attending or hosting the meetings, right?

correct

**Comment by astencel-sumo** [comment]
@trask What is the status of this? Last meeting recording is from May 25th. I want to access the May 31st Collector SIG.

> ya, it hit the monthly limit on my free account. we've opened a request to the CNCF to upgrade us to a paid account.

Is this where we're at at the moment?

**Comment by trask** [comment]
> @trask What is the status of this? Last meeting recording is from May 25th. I want to access the May 31st Collector SIG.
> 
> > ya, it hit the monthly limit on my free account. we've opened a request to the CNCF to upgrade us to a paid account.
> 
> Is this where we're at at the moment?

ya, CNCF is working through a new internal finance process which is why it's taking a while, they have assured us that they are still working on this

if you (or anyone) needs a specific recording in the meanwhile, ping me on Slack and I can pull it for you

**Comment by tylerbenson** [comment]
Is there someone at Google that could help here?  Would be really nice to get this fixed soon.

**Comment by trask** [comment]
we got paid Zapier account from CNCF yesterday, I'm currently working on updating things and we should be able to merge this PR in the next few days

**Comment by trask** [comment]
@weyert can you open a new issue about not being able to access the recordings now that the only place to view them is on https://zoom.us?

**Pull request merged**
