### PR TITLE
Clarify maintainer role in github teams

### PR DESCRIPTION
**Pull request by trask**
I think this is the current practice but isn't documented and came up in https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1720257247004479?thread_ts=1720120170.039779&cid=C01NJ7V1KRC

### CODE REVIEW

**Review by svrnm — COMMENTED** [review]
Thanks! We might want to review all the teams if they follow that structure or if any need fixing

**Review by svrnm — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Review by danielgblanco — APPROVED** [review]

**Comment by danielgblanco** [comment]
Should we merge this and then go ahead and make sure all teams are setup like that? I think needs a TC member to do it.

**Comment by tsloughter** [comment]
What @danielgblanco said. For example, I don't have permission to add maintainers to `erlang-contrib-maintainers`

**Review by carlosalberto — APPROVED** [review]

**Comment by trask** [comment]
> Should we merge this and then go ahead and make sure all teams are setup like that? I think needs a TC member to do it.

I created #2205

**Comment by trask** [comment]
> I don't have permission to add maintainers to `erlang-contrib-maintainers`

@tsloughter you should have permission now

**Pull request merged**
