### PR TITLE
Corrected Comms SIG meeting time

### PR DESCRIPTION
**Pull request by melbgirl**
Was 10:30, has been 10:15 for a while.

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by dyladan** [comment]
@austinlparker when is the meeting time changing? probably makes sense to try to keep the repo as current as possible but maybe we can open a draft that reflects the new time

**Comment by svrnm** [comment]
From now on we will meet on every other Monday 10-11am US PT, so we can update it to that

**Comment by svrnm** [comment]
@melbgirl can you update the PR to say that we now meet on monday 10-11am PST?

**Comment by dyladan** [comment]
@svrnm I was going to update it myself but it wasn't clear from your message, do you mean every monday or is it still every other monday?

**Comment by dyladan** [comment]
Nevermind I see

**Review by dyladan — APPROVED** [review]

**Pull request merged**
