### PR TITLE
Decentralize Ruby Maintainers and approvers list

### PR DESCRIPTION
**Pull request by mwear**
@dazuma is the top contributor to OpenCensus Ruby and has been helping with infrastructure on OpenTelemetry Ruby. We'd be happy to have him as a maintainer.

See:
* https://github.com/census-instrumentation/opencensus-ruby/graphs/contributors
* https://github.com/census-instrumentation/opencensus-ruby/commits?author=dazuma
* https://github.com/open-telemetry/opentelemetry-ruby/pull/124
* https://github.com/open-telemetry/opentelemetry-ruby/pull/138

### CODE REVIEW

**Comment by fbogsany** [comment]
I second this nomination for the reasons outlined by @mwear

**Comment by dazuma** [comment]
Linking https://github.com/open-telemetry/community/issues/242

**Comment by dazuma** [comment]
Oh, looks like #241 was already done. Thanks everyone! The things that happen while one is asleep...

**Comment by mwear** [comment]
The contributor list has been moved to OTel Ruby in this PR: https://github.com/open-telemetry/opentelemetry-ruby/pull/139.

**Pull request merged**
