### PR TITLE
add jaredtan to candidates list.

### PR DESCRIPTION
**Pull request by JaredTan95**

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Please rebase from the head of main branch

**Comment by JaredTan95** [comment]
> Please rebase from the head of main branch

ok

**Comment by lizthegrey** [comment]
hate to ask this, but this was merged without ratification. Is the intention to check ratification at end of nomination period, or before accepting candidates?

**Comment by yurishkuro** [comment]
@lizthegrey you're right, my bad. I think it's better to undo the merge and wait for ratification.

**Comment by yurishkuro** [comment]
reverted and reopened as #1217

**Pull request merged**
