### PR TITLE
Update link to registration form

### PR DESCRIPTION
**Pull request by irabinovitch**
Updating docs with the correct link to the registration form so its easier for find. Right now link points to an issue, where you have to dig for the form again.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@bhs FYI since you are running the election committee.

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by bhs** [comment]
Thanks – missed that when I created the form. :-/

**Review by bhs — APPROVED** [review]

**Comment by bhs** [comment]
@irabinovitch there's an EasyCLA issue... I will just make this change myself so we can get it in.

image

**Comment by bhs** [comment]
@SergeyKanzhelev or others, can you approve my change (#550) so I can merge? Thanks...

**Comment by irabinovitch** [comment]
Fixed the Easy CLA stuff too.

**Pull request closed without merging**
