### PR TITLE
Add client instrumentation (RUM) SIG to community list

### PR DESCRIPTION
**Pull request by mtwo**
The SIG already exists, just adding it to the official SIG list. No Zoom link as these will all be changing to ephemeral links over the weekend.

### CODE REVIEW

**Comment by arminru** [comment]
@mtwo The new branch protection rules added by the CNCF won't let you push on this branch to resolve the merge conflict. You'll have to open a new PR (ideally from a fork so you'd be able to resolve future conflicts).

**Comment by mtwo** [comment]
Update: will redo this PR and update the Zoom links later this week, as I have a per-requisite task to create a shared Google account

**Comment by vinaya-devopsnow** [comment]
Does this meeting consider DST for 9.00 AM PT ?

**Comment by arminru** [comment]
@mtwo Seems like this was overlooked, could update you please resolve the conflicts?

**Comment by mtwo** [comment]
I've replaced this change set with #913, which also won't suffer from the same branch protection issue

**Pull request closed without merging**
