### PR TITLE
Update my profile photo with a working link + alphabetized order

### PR DESCRIPTION
**Pull request by reese-lee**
For some reason my profile picture won't show up with the `static/candidate-picture.png` format, so I updated the link. I also corrected the alphabetical order of names at the top.

### CODE REVIEW

**Comment by reyang** [comment]
> For some reason my profile picture won't show up with the `static/candidate-picture.png` format, so I updated the link. I also corrected the alphabetical order of names at the top.

Have you uploaded your photo to the repo? It seems the file does not exist https://github.com/open-telemetry/community/tree/main/elections/2022/static.

**Comment by reese-lee** [comment]
@reyang I completely spaced on the process. Done now!

**Review by reyang — APPROVED** [review]
LGTM, need to apply the changes from #1245 and #1246 to avoid merge conflicts.

**Comment by reese-lee** [comment]
Created new PR to avoid conflicts.

**Pull request closed without merging**
