### PR TITLE
Add more CI/CD tracing examples

### PR DESCRIPTION
**Pull request by egorklimov**
Hey all!

I've added a few examples of CI/CD tracing: two related to [TeamCity](https://www.jetbrains.com/teamcity/) and one that covers all Datadog CI tracing plugins. Perhaps each Datadog CI tracing plugin deserves its own row in the table.

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Comment by arminru** [comment]
@adrielp FYI

**Comment by svrnm** [comment]
would be great to have those from that list where it is applicable added to the registry:

https://opentelemetry.io/ecosystem/registry/adding/

**Review by svrnm — APPROVED** [review]

**Comment by arminru** [comment]
cc @open-telemetry/semconv-cicd-approvers

**Review by adrielp — APPROVED** [review]
It's fine to add them as references! LGTM.

**Pull request merged**
