### PR TITLE
Adding OpenTelemetry logo files

### PR DESCRIPTION
**Pull request by mtwo**
Useful for marketing materials, website updates, etc. These were originally created by C. Craig Ross on behalf of the CNCF.

### CODE REVIEW

**Comment by mtwo** [comment]
@austinlparker FYI

**Comment by SergeyKanzhelev** [comment]
Great! Can you also have a document with the online links to it? For instance, this is what we use in .NET:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/26f00c433aa328ebab6255b1e451db00a530c855/build/Common.prod.props#L31

**Comment by yurishkuro** [comment]
Is there anything new here that's not already available from the CNCF official artwork repo?

https://github.com/cncf/artwork/tree/master/projects/opentelemetry

**Comment by mtwo** [comment]
Nice find - I didn't realize that the CNCF already had these on GitHub. Reverting the PR!

**Comment by bhs** [comment]
@mtwo I still think it would be nice to make these more discoverable... maybe a link from the community README?

**Comment by yurishkuro** [comment]
+1 to link in readme, but host in the official CNCF repo

**Comment by bhs** [comment]
I created https://github.com/open-telemetry/community/pull/244 if someone wants to do a very quick rubberstamp...

**Comment by bhs** [comment]
rubberstamped and merged :) (Thanks, Bogdan)

**Pull request closed without merging**
