### PR TITLE
fix java calendar link

### PR DESCRIPTION
**Pull request by zeitlinger**
fix java calendar link

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@zeitlinger can you please sign CLA

**Comment by zeitlinger** [comment]
> Alternatively you can use this link: https://calendar.google.com/event?action=TEMPLATE&tmeid=aGlqamsyYTV0dDh0ZDM1YmpkZWRjN2wyNjhfMjAyMDA0MTBUMTUwMDAwWiBnb29nbGUuY29tX2I3OWUzZTkwajdiYnNhMm4ycDVhbjVsZjYwQGc&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com&scp=ALL Small problem is that it will require auth

yes, that is one click faster.
Should we change all calendar links to this format?

**Comment by SergeyKanzhelev** [comment]
@zeitlinger I remember complains that links must not require auth with Google account. So perhaps this may be an alternative link. If you want to send an additional PR - it would be great. Merging this one for now.

**Comment by zeitlinger** [comment]
> @zeitlinger I remember complains that links must not require auth with Google account. So perhaps this may be an alternative link. If you want to send an additional PR - it would be great. Merging this one for now.

2 links could also be confusing, so I'd leave it at that.
All you have to do is click on "more details" to add it to your calendar.

**Pull request merged**
