### PR TITLE
Update logs doc

### PR DESCRIPTION
**Pull request by dyladan**
Related #1147 
Logs doc previously owned by @tigrannajaryan recreated because it could not be transferred

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]

**Review by arminru — APPROVED** [review]
Please make sure to also update the calendar invite.

**Comment by tigrannajaryan** [comment]
I added a notice at the top of the old document with a link to the new document. Also made the old document readonly.
Let's merge this PR and update the calendar.

**Comment by tigrannajaryan** [comment]
I updated the calendar.

**Comment by dyladan** [comment]
Needs 1 more review to merge

**Comment by dyladan** [comment]
Calendar is already updated so we need to do this ASAP

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee we need one more approval to merge this.

**Review by trask — APPROVED** [review]

**Pull request merged**
