### PR TITLE
Repository settings guidelines: Apply rules also to branch creation

### PR DESCRIPTION
**Pull request by arminru**
This setting enables the branch protection rule to not only cover PRs targeting an existing branch, but also the creation of new branches.

For the `main` branch, this doesn't make a difference as it will usually be there, but for the `**/**` pattern, as per https://github.com/open-telemetry/community/blob/8e17c3051426def819b6e0fe6eb652d950d28975/docs/how-to-configure-new-repository.md#L119-L121 the rules for `main` are re-used.

Docs:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

### CODE REVIEW

**Review by danielgblanco — APPROVED** [review]

**Review by lmolkova — APPROVED** [review]

**Review by austinlparker — APPROVED** [review]

**Comment by jpkrohling** [comment]
Wouldn't it prevent dependabot and similar tools from working? They push PRs from branches they create on the target repo, from what I remember.

**Comment by austinlparker** [comment]
> Wouldn't it prevent dependabot and similar tools from working? They push PRs from branches they create on the target repo, from what I remember.

If you're using dependabot you can make a branch protection rule for its branches specifically.

**Comment by jpkrohling** [comment]
Sounds good. As long as we are not breaking current tools with this change, I'm fine with the change.

**Comment by arminru** [comment]
@jpkrohling exactly as @austinlparker said - the rules for Dependabot and Renovate overrule the `main` and the `**/**` catchall rule:

https://github.com/open-telemetry/community/blob/3f4b5283455c7119f61994c1eac7dc55115af4f9/docs/how-to-configure-new-repository.md#L98-L117

**Review by jpkrohling — APPROVED** [review]

**Comment by danielgblanco** [comment]
@arminru can you create an issue to apply this to all repos and link it here?

**Comment by arminru** [comment]
@danielgblanco Done! https://github.com/open-telemetry/community/pull/2178

**Pull request merged**
