### PR TITLE
Nominating Ilan Rabinovitch

### PR DESCRIPTION
**Pull request by CharlyF**
Adding Ilan Rabinovitch to the list of nominees for the OpenTelemetry Governance Committee.

### CODE REVIEW

**Comment by bhs** [comment]
Thank you for the nomination, @CharlyF!

@irabinovitch, since this was not a self-nomination, can you confirm your desire to run by making a short comment here?

We'll also need ratification from members of standing representing distinct companies (that aren't Datadog). To be clear, that ratification deadline is *not* today, so not urgent.

**Comment by irabinovitch** [comment]
👍  Thanks @CharlyF and @bhs

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
PR was created and candidate confirm the desire before the deadline expired.

**Comment by bhs** [comment]
@bogdandrutu merging at this point was not the protocol described in [the doc describing the election process](https://github.com/open-telemetry/community/blob/master/elections/2020/governance-committee-election.md#nominations):

>The Pull Request will not be merged until the candidate has confirmed their desire to be nominated (if not self-nominating) **and ratification has occurred via PR comments.**

I.e., we were supposed to wait until the PR+nomination had been ratified prior to the Oct 19 deadline.

Anyway, no big deal – but @irabinovitch @CharlyF: before Oct 19, please find two members of standing from the OTel community who work at two different companies (other than Datadog) who will ratify the nomination. It's fine for them to just add a short comment or 👍 to this PR (even though it's been merged).

**Comment by bhs** [comment]
@CharlyF @irabinovitch ping on ^^^

The list of nominees is supposed to be finalized today, so we need the ratifications soon. Thanks.

**Comment by bhs** [comment]
@mayurkale22 @bogdandrutu : you both "GitHub-emoji-reacted" to [my message above](https://github.com/open-telemetry/community/pull/540#issuecomment-709542234) on this PR.

Were those 🎉 and 👍 your way of ratifying? :)  Please confirm, as that would give Ilan the three ratifications required.

**Comment by mayurkale22** [comment]
Please consider 👍 as my ratification for Ilan Rabinovitch.

**Comment by sarahnovotny** [comment]
+1

**Comment by bhs** [comment]
Okay, we're all set – thanks @sarahnovotny @mayurkale22 !

**Pull request merged**
