### PR TITLE
Self-nomination: Trask Stalnaker for Governance Committee 2022

### PR DESCRIPTION
**Pull request by trask**

### CODE REVIEW

**Comment by jkowall** [comment]
I concur! You should have asked @trask :)

**Comment by lizthegrey** [comment]
I third.

**Review by lizthegrey — APPROVED** [review]
Three members of standing have ratified, including one self-ratification.

**Comment by heyams** [comment]
I support this nomination 👍

**Comment by jeremydvoss** [comment]
I support this nomination

**Comment by cijothomas** [comment]
I support!

**Comment by rajkumar-rangaraj** [comment]
I support this nomination.

**Comment by vishweshbankwar** [comment]
I support this nomination

**Comment by jeanbisutti** [comment]
I strongly support this nomination. Trask is a great facilitator of the OpenTelemetry Java and Instrumentation SIG. He welcomes new contributions.

**Pull request merged**
