### PR TITLE
Added OTel contribution details for Alolita Sharma

### PR DESCRIPTION
**Pull request by alolita**

### CODE REVIEW

**Review by bhs — APPROVED** [review]

**Comment by bhs** [comment]
@alolita since voting opens in about 8h, I was hoping to merge this soon. In lieu of other reviewers, I just wanted to briefly verify the contributions you're referring to. Are you able to point to a few representative PRs you've made to the OTel C++ API+SDK and the prometheus work? (Just in the thread here – _not_ suggesting that needs to go into the text of the nomination bio, to be clear)

**Comment by alolita** [comment]
Hi @bhs I manage and guide the engineering team that has contributed to OTel projects. Here are some examples of the contributions my team has made under my guidance.
https://github.com/open-telemetry/opentelemetry-collector/pull/1577
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/205
https://github.com/open-telemetry/opentelemetry-cpp/pull/191

**Comment by bhs** [comment]
I'm glad for others to jump in here, but IMO there is an important distinction between "managing a team that makes contributions" and "making those contributions oneself." So can that be clarified? Basically the difference between something like

> I’ve contributed Prometheus pull and remote-write exporters for the C++, Go SDKs and the Collector.

... and ...

> My team has contributed Prometheus pull and remote-write exporters for the C++, Go SDKs and the Collector.

**Comment by tedsuo** [comment]
Pedantic but probably correct @bhs. :)

**Comment by bhs** [comment]
@alolita congrats on your recent election to the GC! I am going to close this since voting is over...

**Pull request closed without merging**
