### PR TITLE
Added Prometheus WG info to list of SIG meetings

### PR DESCRIPTION
**Pull request by alolita**
Added OTEL-Prometheus workgroup meeting and notes details.

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Review by dyladan — APPROVED** [review]

**Comment by mtwo** [comment]
FYI @alolita you'll need to rebase this for it to be merged

**Comment by yurishkuro** [comment]
@alolita could you please resolve merge conflicts? Alternatively, maybe because your branch is protected GH does not enable the usual Merge button here.

**Comment by dyladan** [comment]
@alolita there are still merge conflicts

**Comment by dyladan** [comment]
@yurishkuro the problem is actually that the branch was created on the community repo directly not on a fork so it can't be updated without a CLA check. This PR will never be mergeable and should be replaced

**Comment by trask** [comment]
> @yurishkuro the problem is actually that the branch was created on the community repo directly not on a fork so it can't be updated without a CLA check. This PR will never be mergeable and should be replaced

Replaced by #1316

**Pull request closed without merging**
