### PR TITLE
[election] lizf stands for re-election

### PR DESCRIPTION
**Pull request by lizthegrey**

### CODE REVIEW

**Comment by austinlparker** [comment]
+1

**Comment by Aneurysm9** [comment]
thirded!

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
Ratified by @lizthegrey (honecomb.io), @austinlparker (Splunk), @Aneurysm9 (Independent).

**Comment by bhs** [comment]
@SergeyKanzhelev one minor correction: Austin works for Lightstep, but we have still met the ratification requirements.

**Comment by lizthegrey** [comment]
> @SergeyKanzhelev one minor correction: Austin works for Lightstep, but we have still met the ratification requirements.

I ninja fixed it

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev one minor correction: Austin works for Lightstep, but we have still met the ratification requirements.

somehow I was thinking of Bogdan while writing it. Sorry

**Comment by bhs** [comment]
@lizthegrey the GH PR preview didn't reveal the scale of the jpg... do you mind making your image approx the height of the others? Current looks like this on desktop:



NBD / no rush!

**Comment by flands** [comment]
late to the party, but 👍  (fourthed?)

**Pull request merged**
