### PR TITLE
Nominate flands for GC 2023

### PR DESCRIPTION
**Pull request by atoulme**
I would like to make the recommendation that we nominate Steve Flanders (@flands) for GC 2023.

Steve ran in 2021, on the platform I copy below. Steve has deep interest and history with the OpenTelemetry project, and was my inspiration and my guide as I discovered this ecosystem. I would like for Steve to consider this nomination and I would want him to run on the basis of his role and large influence at Splunk, with users, adopters and the ecosystem at large.

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
@flands, please confirm you are OK with the nomination before we can merge this PR.

**Comment by flands** [comment]
Thanks @atoulme ! I accept the nomination.

**Comment by jpkrohling** [comment]
I support

**Review by codeboten — APPROVED** [review]

**Review by trask — APPROVED** [review]
endorsed by 3 members of standing from 3 different employers

**Comment by codeboten** [comment]
I support

**Pull request merged**
