### PR TITLE
Proposal: React Native SIG

### PR DESCRIPTION
**Pull request by jpmunz**
Hey everyone,

No sponsors for this yet but wanted to get it up to gauge interest and have a conversation about usefulness here. I had written a blog post here that goes over a bit of the current state and challenges of opentelemetry instrumentation on React Native using the OTEL demo project as an example: https://www.cncf.io/blog/2024/08/05/how-to-add-otel-instrumentation-to-a-react-native-app/

In addition this PR for adding an instrumentation library for navigation changes in React Native gives an example of the kind of work this SIG would try and drive: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2359

### CODE REVIEW

**Comment by trask** [comment]
cc @open-telemetry/javascript-approvers

**Comment by danielgblanco** [comment]
@jpmunz have you been able to find support from other contributors (preferably from more than one company) to join this SIG?

**Comment by jpmunz** [comment]
> @jpmunz have you been able to find support from other contributors (preferably from more than one company) to join this SIG?

hey @danielgblanco not as of yet, we've been discussing next steps for this in the JS SIG meetings and trying to get further sponsorship

**Comment by jpmunz** [comment]
After discussion I'll close this PR for now due to lack of staffing beyond myself and @facostaembrace as well as not having a strong immediate need for a weekly meeting + dedicated repo.

Ideally would still like to try and get a dedicated project board up at the org level to track React Native specific initiatives which will continue to be worked on within the existing JS SIG. I'll plan to revisit this proposal if those contributions generate stronger interest / a need for a more targeted working group

**Pull request closed without merging**
