### PR TITLE
update meeting time

### PR DESCRIPTION
**Pull request by cartersocha**
update demo meeting time

### CODE REVIEW

**Comment by cartersocha** [comment]
@austinlparker can you update the calendar?

**Review by arminru — APPROVED** [review]

**Comment by arminru** [comment]
> @austinlparker can you update the calendar?

@cartersocha Is it 30mins now or still 45mins?

**Comment by cartersocha** [comment]
30 mins. 830-9

**Review by trask — APPROVED** [review]

**Comment by arminru** [comment]
> 30 mins. 830-9

@cartersocha Calendar invite updated ✅

**Pull request merged**
