### PR TITLE
Replace JS gitter with Discussions

### PR DESCRIPTION
**Pull request by dyladan**
Following the example of Java (#587), The JS community has made the decision to move from Gitter to Discussions.

/cc @obecny

### CODE REVIEW

**Review by obecny — APPROVED** [review]

**Comment by yurishkuro** [comment]
Those are not really equivalent media, but if the OTEL JS community simply does not have a need for real time chat, I think it's fine to remove it. I am not sure it's worth listing Discussions in the summary though, they are just a tool within GitHub like Issues, people should  know how to use those already (it may be helpful to setup issues template to direct people to discussions for questions, e.g. https://github.com/jaegertracing/jaeger/issues/new/choose)

**Comment by Oberon00** [comment]
I think Github Discussions (like PRs, issues) do have realtime features though? Like if someone comments while you have it open, the new comment will appear without you needing to refresh.

**Comment by dyladan** [comment]
> Those are not really equivalent media, but if the OTEL JS community simply does not have a need for real time chat, I think it's fine to remove it.

Most of the discussion in gitter has already been in question/answer format. The JS SIG itself rarely if ever uses it to discuss among ourselves. Moving these questions to GitHub makes them more easily searchable and useful over a longer period of time. It also prevents questions from getting lost to the chat history.

> I am not sure it's worth listing Discussions in the summary though, they are just a tool within GitHub like Issues, people should know how to use those already (it may be helpful to setup issues template to direct people to discussions for questions, e.g. [jaegertracing/jaeger/issues/new/choose](https://github.com/jaegertracing/jaeger/issues/new/choose))

I am just following the example of Java #587

**Comment by SergeyKanzhelev** [comment]
whatever @open-telemetry/javascript-maintainers decide. Also fix the README.md in Javascript repository than to indicate that discussions are preferred like Java did

**Review by vmarchaud — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
Maintainers want this change. So happy to merge this. 

Please make sure to update the readme in SIG repositories to point to discussions instead of Gitter

**Pull request merged**
