### PR TITLE
Self-nomination: Reiley Yang for Governance Committee 2022

### PR DESCRIPTION
**Pull request by reyang**
Self nomination with statement of candidature for Reiley Yang.

### CODE REVIEW

**Comment by lalitb** [comment]
I support this nomination!

**Comment by svrnm** [comment]
I support this nomination!

**Comment by Kielek** [comment]
I support this nomination!

**Comment by ThomsonTan** [comment]
I support this nomination!

**Comment by jpkrohling** [comment]
The intent of the schedule was to close nominations on 6 Oct 2022, but I missed the other place mentioning the deadline for the nominations (7 Oct 2022 23:59 UTC). Therefore, this nomination is still valid provided it receives the necessary support.

https://github.com/open-telemetry/community/blob/main/elections/2022/governance-committee-election.md#schedule

**Comment by cijothomas** [comment]
I support this nomination!

**Review by cijothomas — APPROVED** [review]

**Review by yurishkuro — APPROVED** [review]
+1

please rebase

**Comment by reyang** [comment]
@yurishkuro rebase done. I also noticed that the candidate names are not ordered alphabetically. I've made some minor improvements. Will send a separate editorial PR to fix the other parts.

**Comment by CodeBlanch** [comment]
I support this nomination!

**Comment by bogdandrutu** [comment]
+1

**Comment by bogdandrutu** [comment]
Enough +1s

**Comment by TimothyMothra** [comment]
I support this nomination!

**Comment by utpilla** [comment]
I support this nomination!

**Comment by heyams** [comment]
I support this nomination!

**Pull request merged**
