### PR TITLE
 Nominate Ted Young for governance committee

### PR DESCRIPTION
**Pull request by tedsuo**
Hello!

I'd like to continue my work as part of the OpenTelemetry Governance Committee, so I'm adding my nomination to the list.

Cheers,
-Ted

### CODE REVIEW

**Review by dyladan — APPROVED** [review]
Seconded :)

**Review by tigrannajaryan — APPROVED** [review]

**Review by mtwo — APPROVED** [review]
I support!

**Comment by lizthegrey** [comment]
Supported.

**Review by lizthegrey — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Merging to avoid merge conflicts when other nominations arrive.

**Pull request merged**
