### PR TITLE
Adding myself (@MovieStoreGuy) as a nominee for 2022 governance election

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
I would love to help be part of governance committee as especially as the Profiling otep I raised is now being made part of the vision of Open Telemetry.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
I support this nomination.

**Comment by bogdandrutu** [comment]
+1

**Review by lizthegrey — APPROVED** [review]
Please rebase.

Three members of standing have ratified including one self-ratification.

**Comment by jpkrohling** [comment]
I also support this nomination.

**Comment by MovieStoreGuy** [comment]
> Please rebase.
> 
> Three members of standing have ratified including one self-ratification.

Should be fixed and in the correct order.

**Pull request merged**
