### PR TITLE
Self-nomination: Marylia Gutierrez for Governance Committee 2024

### PR DESCRIPTION
**Pull request by maryliag**

### CODE REVIEW

**Comment by lmolkova** [comment]
I support!

**Comment by jpkrohling** [comment]
I know my support doesn't officially count as I belong to the same company, but I also support!

**Comment by janssenlima** [comment]
I support

**Review by jpkrohling — APPROVED** [review]

**Comment by EzzioMoreira** [comment]
I suporte!!!!

**Review by trask — APPROVED** [review]

**Comment by mjlogan** [comment]
I support!

**Pull request merged**
