### PR TITLE
Nominate Isobel Redelmeier as Specification approver

### PR DESCRIPTION
**Pull request by tedsuo**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think for specifications we want to keep only the TC members as maintainers. @SergeyKanzhelev what is your thought here?

**Comment by SergeyKanzhelev** [comment]
Yes for maintainers.  If @tedsuo nominates @iredelmeier as approver - I think it's fine. More eyes of experienced and committed people are better.  As discussed https://github.com/open-telemetry/community/issues/41 specs repo may be quite unique in this sense and we may need more approvals than in any other repository.

Also approvers may be a step to TC. We yet to discuss how TC will be formed going forward.

@bogdandrutu are you OK with this for now?

**Comment by tedsuo** [comment]
ping @bogdandrutu; does adding Isobel as an approver work for you? :)

**Comment by SergeyKanzhelev** [comment]
@tedsuo we are having some offline conversations on how to structure this repository the best way from responsibilities, commitments, openness, fairness and transparency perspective. 

In other words, we are having a non-transparent conversation on how to make decisions making transparent =). Joking aside, making process fair require some discussion that may be seen as sensitive. It is important to make an RFC process work great. We will publish some decisions soon, some of those discussions are slow down by KubeCon.

**Comment by bogdandrutu** [comment]
@tedsuo please rebase.

**Pull request merged**
